# Generated by Django 3.1 on 2022-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_module',
            fields=[
                ('questionId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=150)),
                ('text', models.JSONField(default=[], null=True)),
                ('buttons', models.JSONField(default=[], null=True)),
                ('type', models.CharField(default='', max_length=150)),
                ('functionCall', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
