# Generated by Django 3.1 on 2022-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_module',
            name='category',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='chat_module',
            name='functionCall',
            field=models.JSONField(default=[], null=True),
        ),
    ]
