# Generated by Django 3.1.4 on 2022-11-06 01:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goalSubscriber',
            fields=[
                ('subscriptionKey', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('subscribedDate', models.DateField()),
                ('resources', django_mysql.models.ListCharField(models.CharField(max_length=500), default='', max_length=50500, size=100)),
            ],
        ),
    ]
