# Generated by Django 3.1.4 on 2022-07-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipsubscriber',
            name='tipsShared',
        ),
        migrations.AddField(
            model_name='tipsubscriber',
            name='tipsShared',
            field=models.ManyToManyField(to='tips.Tip'),
        ),
    ]
