# Generated by Django 3.1.4 on 2022-07-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('tipId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tipSubscriber',
            fields=[
                ('phoneNumber', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('subscribedDate', models.DateField()),
                ('tipsShared', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.tip')),
            ],
        ),
    ]
