# Generated by Django 3.1 on 2022-03-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(default='', max_length=255)),
                ('chat_file', models.FileField(upload_to='')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_message', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
