# Generated by Django 3.1 on 2022-03-24 23:54

import bug_reporting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='report_date',
        ),
        migrations.AlterField(
            model_name='bugs',
            name='chat_file',
            field=models.ImageField(blank=True, null=True, upload_to=bug_reporting.models.upload_path),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='report_message',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
    ]
