# Generated by Django 3.1 on 2022-01-14 23:26

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=150)),
                ('lastname', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('savedResources', django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=110, size=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
