# Generated by Django 3.1 on 2022-01-14 23:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savedResources',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), default='', max_length=50500, size=100),
        ),
    ]
